### ISSUE TITLE
Eelarve sisestuse jaoks andmebaasi loomine

### ISSUE THREAD

**Issue by arturrohtla** [arturrohtla/Tarkvaratehnika#3]
Sisestatud andmete salvestamine andmebaasi, nende liigitamine

**Comment by kokolp** [comment]
Panen sql fail, aga ei oska veel kuidas panna esimesel iteratsiooni sisse.

**Comment by kokolp** [comment]
[db.txt](https://github.com/arturrohtla/Tarkvaratehnika/files/829116/db.txt)

**Comment by mariak4s** [comment]
Lisasin su pull requesti selle SQL koodiga failidesse :)
